version: 2

jobs:
  build:
    docker:
      - image: circleci/node4.8.2
        auth:
          username: mydockerhub-temporarykrane
          password: $DOCKERHUB_Puhbyk-focji7-xecrog
    steps:
      - checkout
      - run: echo "Hello, World"
  # test:
  #   docker:
  #     - image: cimg/<language>:<version TAG>
  #       auth:
  #         username: mydockerhub-user
  #         password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  #   steps:
  #     - checkout
  #     - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build