version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    working_directory: ~/backend
    docker:
      # - image: cimg/node:15.8.0
      - image: circleci/python:3.9.0
        auth:
          username: temporarykrane
          password: Puhbyk-focji7-xecrog
    steps:
      - checkout
      - run: echo "Hello, World"
      # - run: npm i
      # - run: node -v
      # - run: "sudo npm install -g npm@latest"
      - run: python3 --version
      - run: cd backend
      - run: ls
      - run: sudo pip install pipenv
      - run: pipenv install
      - run: pipenv run python server.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

         
  # test:
  #   docker:
  #     - image: cimg/<language>:<version TAG>
  #       auth:
  #         username: mydockerhub-user
  #         password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  #   steps:
  #     - checkout
  #     - run: <command>
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build